### ISSUE TITLE
Make sure that large images included in posts are limited to the content width

### ISSUE THREAD

**Issue by kennethlarsen** [ember-learn/empress-blog-ember-template#18]
https://empress-blog-ember-template.netlify.com/the-editor

**Comment by mansona** [comment]
I think other ghost templates solve this by using a "max-width: 100%" rule somewhere 🤔 I think it should be easy enough to put a `blog-post-body > img` rule in. 

related, we might want to make sure that https://github.com/ember-learn/empress-blog-ember-template/blob/master/app/templates/post.hbs#L19 uses `tagName=''` so that we don't have an extra div wrapper (just something that I noticed from other template implementations 👍 )

**Comment by akankshadharkar** [comment]
Hi everyone! 
I'll be taking up this issue 😁

**Comment by mansona** [comment]
Hey @akankshadharkar 👋  did you get a chance to take a look at this issue? would you like any help with it?

**Comment by akankshadharkar** [comment]
Hi Chris, thanks for checking up on this 😄 
Unfortunately I'd been a little more occupied than usual these last days but I'll be working on this on the coming weekend for sure and update you with the progress then
Will let you know if I need any help 🤞

**Comment by akankshadharkar** [comment]
@mansona Have submitted a PR
Please review and let me know if any further changes are required 😄
